### ISSUE TITLE
:)

### ISSUE THREAD

**Issue by otakunami777** [freearhey/iptv#11]
Requesting all Canada/USA channels
and a permalink for Android users so it can sync all channels in one apk
https://pastebin.com/raw/0AxHuqZv (example)

**Comment by freearhey** [comment]
"All in one" playlist already exists:
https://raw.githubusercontent.com/freearhey/iptv/master/index.all.m3u

**Comment by otakunami777** [comment]
Thanks how festive

**Comment by freearhey** [comment]
There are around 6000 channels and only 1400 of them are Chinese. But if you want you can simply load a playlist for a specific country from this list - [https://github.com/freearhey/iptv#playlists-by-country](https://github.com/freearhey/iptv#playlists-by-country)

**Comment by otakunami777** [comment]
I'll just make a custom list and load it that way
