### ISSUE TITLE
how do the epg codes work?

### ISSUE THREAD

**Issue by 1000mbps** [freearhey/iptv#125]
I'm unsure how epg-codes.csv works, is there a way to get it running? cheers

**Comment by freearhey** [comment]
This is just a list, it cannot be executed. 

It was previously planned that this file will be just a source of EPG codes for all channels, but it was decided to use the EPG files themselves. So now this file is deprecated and already deleted from the repo.

**Comment by 1000mbps** [comment]
> This is just a list, it cannot be executed.
> 
> It was previously planned that this file will be just a source of EPG codes for all channels, but it was decided to use the EPG files themselves. So now this file is deprecated and already deleted from the repo.

No worries mate, thanks for the fast reply. EPG isn't 100% needed any way
