### ISSUE TITLE
No sound on Nicktoons US

### ISSUE THREAD

**Issue by koloag27** [freearhey/iptv#126]
There's no sound on US Nicktoons, I tried with VLC and smplayer on PC & VLC on Android and none of them have sound, please fix it if you can.
https://api.vpnmate.com/play/?vlc=1&channel=3005813&token=Bdf4vqpoh8_R:ODFiMDEyNjI1Yjg3NTlhMmJmNTJiZDFmYzE0OWZmNDY0YjY5YWFlMA==

**Comment by freearhey** [comment]
Unfortunately, I can not do anything with this broadcast since I have no control over it. I can only try to find another link to this channel, but I can’t promise anything.
