### ISSUE TITLE
Investigation, Comedy Central and other channels disappeared

### ISSUE THREAD

**Issue by 1000mbps** [freearhey/iptv#133]
Are they down? Cheers

**Comment by koloag27** [comment]
Idk, i wanted to watch NBC Sports but it's missing, same with Nickelodeon & TeenNick.

**Comment by 1000mbps** [comment]
Let's hope it can get fixed quickly, this is on par or better than most paid IPTV services

**Comment by koloag27** [comment]
I hope so, this is the only place i could find these channels.

**Comment by freearhey** [comment]
Unfortunately, links to these channels stopped working and were removed from the playlist. But if I find links to the working broadcasts of these channels, I will return them back.
