### ISSUE TITLE
Channel Listing on Smart STB

### ISSUE THREAD

**Issue by P0987654321** [freearhey/iptv#15]
The links don't seem ideal for Smart STB app and whilst all the channels are there, they are not not stepped by (Tier1) Country > (Tier2) Channel.

Be great if there was a Smart STB portal link. 

Thanks

**Comment by freearhey** [comment]
Sorry, I don't have access to the Smart STB app. It would be great if you gave an example of a playlist that works fine in it.

**Comment by P0987654321** [comment]
An M3U or M3U8 link is ok. 

The app is much better than other IPTV apps. 

G


https://billing.smart-stb.net/index.php/knowledgebase/4/How-to-add-or-change-my-m3u-playlist.html
