### ISSUE TITLE
Suggested iOS app for US residents?

### ISSUE THREAD

**Issue by Amadeus-** [freearhey/iptv#174]
Does anyone have a suggested iOS IPTV app for those residing in the US?   When I try going to the link on the README.md for "Stream - Watch IPTV & Movies", it says This app is currently not available in your country or region.

Would the version of VLC for iOS be the next best choice?

Thanks!

**Comment by freearhey** [comment]
Let me know if you find a suitable application, I will add it to the list.

**Comment by jlapitan** [comment]
this is what i am using https://apps.apple.com/us/app/gse-smart-iptv/id1028734023

**Comment by freearhey** [comment]
@jlapitan Thanks! Added it to the list.
