### ISSUE TITLE
M3U url in IPTV Smarters app

### ISSUE THREAD

**Issue by kerwin-uy** [freearhey/iptv#19]
It does not load the m3u from the url.. it keeps returning File/URL is not valid error message. I've tried all and per country m3u and all does not work.

**Comment by freearhey** [comment]
Could you give some example of a playlist that works in this application? That would help a lot.

**Comment by kerwin-uy** [comment]
It's quite strange.. I couldn't get it to work adding the url directly to the app, but downloading the m3u file first then adding the downloaded file worked for me.

I had hoped that adding the url directly would work so it would be more convenient to refresh the channel list.

https://play.google.com/store/apps/details?id=com.nst.iptvsmarterstvbox

**Comment by tiagomartinho** [comment]
Maybe a problem in the app.

I have developed an iOS IPTV Player as well and it imports/plays every playlist in this repo:
https://moviesstreamapp.com

Hope that it helps!

**Comment by Akashpragh** [comment]
akashprajapat58407@gmail.com
L

**Comment by lbouriez** [comment]
I was having the same issue... I am using ControlD for my DNS and it was blocking the domain.
