### ISSUE TITLE
please add jatttv to india and uk list

### ISSUE THREAD

**Issue by desiflex** [freearhey/iptv#219]
#EXTINF:-1 group-title="Desi" tvg-logo="http://desibox.0hi.me/1.png" ,JattTV.CoM TV Urban Desi Musix [1080p]
http://edge.hls.hitbox.tv/hls/desijattuk/index.m3u8?st=xtJam_iAQGbVTJ5cSRhNpQ;ci=i6oOry555eTOkW7Q1UpqPQ
 
#EXTINF:-1 group-title="Desi" tvg-logo="http://desibox.0hi.me/1.png" ,JattTV.CoM TV Urban Desi Musix [LINK 2]
http://tiny.cc/jattvlink
 
 
#EXTINF:-1 group-title="Desi" tvg-logo="http://desibox.0hi.me/1.png" ,JattTV.CoM TV Urban Desi Musix [LINK 3]
http://ad.mysisli.com/live/DESIBOX/index.m3u8

**Comment by freearhey** [comment]
I would love to add this channel, but:
- the first two streams are very unstable (constantly crashes)
- last link doesn't work at all

**Comment by desiflex** [comment]
1. #EXTINF:-1 group-title="Desi" tvg-logo="http://desibox.0hi.me/1.png"
   ,JattTV.CoM TV Urban Desi Musix [1080p]
   2.
   http://edge.hls.hitbox.tv/hls/desijattuk/index.m3u8?st=xtJam_iAQGbVTJ5cSRhNpQ;ci=i6oOry555eTOkW7Q1UpqPQ


please try now
