### ISSUE TITLE
please add to indian list 

### ISSUE THREAD

**Issue by desiflex** [freearhey/iptv#220]
#EXTINF:-1 group-title="Desi" tvg-logo="http://desibox.0hi.me/1.png" ,JattTV.CoM TV Urban Desi Musix [1080p]
http://edge.hls.hitbox.tv/hls/desijattuk/index.m3u8?st=xtJam_iAQGbVTJ5cSRhNpQ;ci=i6oOry555eTOkW7Q1UpqPQ

**Comment by freearhey** [comment]
It is still buggy and every couple of seconds it stops working.
