### ISSUE TITLE
please add to indian and uk list working fine now

### ISSUE THREAD

**Issue by desiflex** [freearhey/iptv#221]
#EXTINF:-1 group-title="Desi" tvg-logo="http://desibox.0hi.me/1.png" ,JattTV.CoM TV Urban Desi Musix [1080p]
http://edge.hls.hitbox.tv/hls/desijattuk/index.m3u8?st=xtJam_iAQGbVTJ5cSRhNpQ;ci=i6oOry555eTOkW7Q1UpqPQ
 

 
#EXTINF:-1 group-title="Desi" tvg-logo="http://desibox.0hi.me/1.png" ,JattTV.CoM TV Urban Desi Musix [LINK 3]
http://ad.mysisli.com/live/DESIBOX/index.m3u8

**Comment by freearhey** [comment]
The same thing, the stream stops working after a couple of seconds. 

Please try to watch it yourself for at least a couple of minutes before sending a link to this channel again.
