### ISSUE TITLE
Proposal to merge Spanish channels

### ISSUE THREAD

**Issue by mixpc** [freearhey/iptv#25]
Hello,

I've noticed one can find Spain and Spanish-speaking TV channels under...
[https://raw.githubusercontent.com/freearhey/iptv/master/channels/es.m3u](https://raw.githubusercontent.com/freearhey/iptv/master/channels/es.m3u)
in different groupings:
```
group-title="Spain-WebTV"
group-title="SPAIN"
group-title="Spanish(español)"
group-title="News"
group-title=""
group-title="Sport"
group-title="Movies"
group-title="United Arab Emirates PREMIUM-SERVER4"
```

My proposal is to arrange them into:
```
Spain-Spanish (Español)
Spain-Catalan (Catalan)
Spain-Galician (Galego)
Spain-Basque (Euskera)
Spain-Asturian (Asturianu)
```
as these are the languages spoken in those TV channels.

Please, share views and if ok, I will proceed.

**Comment by freearhey** [comment]
Hi! 

I think it is better to group by topic of channel, therefore I left the current list of possible categories in the documentation: https://github.com/freearhey/iptv#contribution

And of course, if you could help and fix the group titles in this playlist to the correct ones, that would be just great.

**Comment by mixpc** [comment]
Good, working on it now. Please, confirm procedure with non-TV channels (i.e. radio stations) such as:
Radio Onda Madrid
ESPAÑA (linking to aac.m3u8 audio)

This is IPTV so I think they don't belong. But please, share your view. If they should stay, maybe a Radio group-title should be added to the wiki?

**Comment by freearhey** [comment]
I agree with you, the radio stations should be removed from the playlist.

**Comment by mixpc** [comment]
Good. Pull request sent.
