### ISSUE TITLE
TVJ and CVM in jamaica channel list and Populate list with epg

### ISSUE THREAD

**Issue by animotionguy** [freearhey/iptv#26]
Would it be possible to add epg to channels or that's too much work 😅. No stress if it is. 

Can TVJ Television Jamaica and CVM TV be added in channel listing

**Comment by freearhey** [comment]
To be honest, I can not even imagine whether the existence of open access EPG for 6000 channels. But if you find anything, let me know and I'll be happy to post it here!

**Comment by animotionguy** [comment]
Okay so I was reading about how to add EPG to the m3u list. I realized that it's not an easy process of just adding the tvg-id within the m3u file and iptv providers usually populate an epg xml with their list of channels which comes at a cost. The best thing I found was webgrab plus (http://webgrabplus.com ) which can auto populates the xml but it seems like a difficult process. I'm not a developer or programmer of sorts but i'll try and figure it out. It seems that it could be integrated on a server that updates a list daily or after a set number of days.

**Comment by gandimohammad** [comment]
USA EPG
[guideusa (1).xml.gz](https://github.com/freearhey/iptv/files/3218942/guideusa.1.xml.gz)

United Kingdom
[guideuk.xml.gz](https://github.com/freearhey/iptv/files/3218943/guideuk.xml.gz)

Sweden
[guidesweden.xml.gz](https://github.com/freearhey/iptv/files/3218944/guidesweden.xml.gz)

Germany
[guidegermany.xml.gz](https://github.com/freearhey/iptv/files/3218945/guidegermany.xml.gz)

France
[guidefrance (1).xml.gz](https://github.com/freearhey/iptv/files/3218946/guidefrance.1.xml.gz)

Arab
[guidearab (1).xml.gz](https://github.com/freearhey/iptv/files/3218947/guidearab.1.xml.gz)

Turkey
[guideturkey.xml.gz](https://github.com/freearhey/iptv/files/3218948/guideturkey.xml.gz)
