### ISSUE TITLE
sports channels

### ISSUE THREAD

**Issue by amirh123123** [freearhey/iptv#28]
please add more sports channels example bt sports sky sports bien sports eleven sports and more and all quality example bien sport 1 hd sd moble and more

**Comment by bdvlstm** [comment]
evet türkiye için spor kanala eklermisin bein spor kanaları

**Comment by amirh123123** [comment]
and bein sport ar 1 to 10 and bein 11 to 13 english and more bein sport and all quality

**Comment by ayaz59** [comment]
Hello freearhey pls turkey chanels add bein sport 🙏

**Comment by bleso** [comment]
Could you make a folder with all sport channels? Same as with countries. cheers

**Comment by freearhey** [comment]
@bleso Done. Here is the link: `https://raw.githubusercontent.com/freearhey/iptv/master/index.sport.m3u`

**Comment by mardinli455** [comment]
bein spot türk yok

**Comment by mardinli455** [comment]
bein sport türk yok

**Comment by ayaz59** [comment]
Neden yok acaba

iPhone’umdan gönderildi

mardinli455 <notifications@github.com<mailto:notifications@github.com>> şunları yazdı (24 Tem 2019 12:27):


bein sport türk yok

**Comment by ayaz59** [comment]
No beınsport tr :(

iPhone’umdan gönderildi

Aleksandr Statciuk <notifications@github.com<mailto:notifications@github.com>> şunları yazdı (24 Tem 2019 12:13):


@bleso<https://github.com/bleso> Done. Here is the link: https://raw.githubusercontent.com/freearhey/iptv/master/index.sport.m3u
