### ISSUE TITLE
Please add more indian channels 

### ISSUE THREAD

**Issue by mysyscomm** [freearhey/iptv#303]
Please check the link given
http://mhdtvworld.com/

**Comment by freearhey** [comment]
Okay, I will do it as soon as I have some free time.

**Comment by mysyscomm** [comment]
OK dear take your time

Thanks
Take care

**Comment by xtremetv** [comment]
yah really waiting for all this channels

**Comment by ik4u** [comment]
patiently awaiting these channels. especially Colors HD one of my favorites
keep up the good work
