### ISSUE TITLE
Source Down

### ISSUE THREAD

**Issue by bmunyoki** [freearhey/iptv#308]
When adding a stream on Xtream codes panel with any of these streams as the source, I get source down error. What could be the issue?

**Comment by adamo331** [comment]
stop adding the streams on this panel, they down quickly and changed due this shit panel. the source is for watching in VLC

**Comment by freearhey** [comment]
@bmunyoki Unfortunately, I can’t help you, because I have never used Xtream codes and I don’t know how it works.
