### ISSUE TITLE
Channel listH

### ISSUE THREAD

**Issue by st8ofgrace** [freearhey/iptv#33]
Hi! The list for US channels is not opening as a "playable" file in VLC...I am a newbie at this, so please tell me if I am missing a crucial step... I am simply copying the m3u file listed by the USA subcategorized list, and opening that stream directly in VLC.  The full list works wonderfully, but it is tedious to go through and delete all of the channels outside of the US streams, so any help would be greatly appreciated.  Thanks for the hard work!

**Comment by freearhey** [comment]
Open VLC -> File -> "Open Network..." and paste `https://raw.githubusercontent.com/freearhey/iptv/master/channels/us.m3u` into URL field.
