### ISSUE TITLE
would like to add this channels

### ISSUE THREAD

**Issue by xtremetv** [freearhey/iptv#339]
http://mhdtvworld.com/genre/jio-tv/
http://mhdtvworld.com/genre/jio-tv/page/2/
http://mhdtvworld.com/genre/jio-tv/page/3/
http://mhdtvworld.com/genre/jio-tv/page/4/

http://mhdtvworld.com/tv-channels/hindi-channels/

http://mhdtvworld.com/genre/star-tv/

http://mhdtvworld.com/genre/zee5/
http://mhdtvworld.com/genre/zee5/page/2/

hi bro would u mind to add this channels. no rush when ever u have time.

really appreciate

**Comment by ik4u** [comment]
I support this request
Thanks
Keep Up the Good Work !!!

**Comment by xtremetv** [comment]
Yes I saw but links I sent those channels are not there in the list. Please if u can look. 
Appreciate your work. 

Sunny
Xtreme Tv Service

**Comment by freearhey** [comment]
@xtremetv I added to the playlists all the streams from this site that were possible. 

The fact is that some links to streams on this site are exposed daily, as a result of which links simply stop working the next day after you copy it. Also, some broadcasts simply do not work anywhere except this site. So I'm sorry, but I won’t be able to add more channels from there.

**Comment by xtremetv** [comment]
Please don’t be sorry 

It’s all good. You doing very good bro. If I will find more sites will post. 
Thanks 

Sunny
Xtreme Tv Service

**Comment by freearhey** [comment]
@xtremetv Okay!
