### ISSUE TITLE
all iptv

### ISSUE THREAD

**Issue by amirh123123** [freearhey/iptv#34]
hi why all iptv in one place removed i go to iptv link but i see name of countries and category please creat all tv chanles in one link thanks

**Comment by freearhey** [comment]
The playlist is in place and available via the same link as before: `https://raw.githubusercontent.com/freearhey/iptv/master/index.all.m3u`

**Comment by freearhey** [comment]
Just in case I also returned the link to "all in one" playlist to the documentation.
