### ISSUE TITLE
undefined channels

### ISSUE THREAD

**Issue by amirh123123** [freearhey/iptv#35]
i open this link with gse smart iptv 
https://raw.githubusercontent.com/freearhey/iptv/master/index.all.m3u
and see some group chanles example music but i see undefined channels more than 5000 channels please add countries categories in this link example iran 15 channels and other countries thanks
this channel in category music 
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="Music",MUSIC TOP
http://live-edge01.telecentro.net.ar/live/smil:musictop.smil/chunklist_w538311571_b364000_sleng.m3u8
and this channels not in a group 
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://aghaniaghani.com/images/logo.png" group-title="Undefined",Aghani Aghani
https://svs.itworkscdn.net/aghanilive/aghanilive/playlist.m3u8
please remove undefined thanks

**Comment by freearhey** [comment]
All channels in `index.all.m3u` playlist are grouped only by topic. And since I alone can not determine the correct topic for all 6000 channels, I decided to mark them as "undefined". 
But if it's more convenient for you, I can just delete this group.

**Comment by amirh123123** [comment]
please add grouping buy country all m3u example
group-title=""afghanestan,Aghani Aghani
https://svs.itworkscdn.net/aghanilive/aghanilive/playlist.m3u8
and remove undefined

**Comment by freearhey** [comment]
If you need playlist grouped by country you can use this link: `https://raw.githubusercontent.com/freearhey/iptv/master/index.m3u`

**Comment by amirh123123** [comment]
i open this link with gse smart iptv and open one of country for example iran but not find any channels 
https://raw.githubusercontent.com/freearhey/iptv/master/index.m3u

**Comment by amirh123123** [comment]
in this link just name of countries

**Comment by freearhey** [comment]
Well then the last option you can use one of the playlists from this list: https://github.com/freearhey/iptv#playlists-by-country

**Comment by freearhey** [comment]
I thought a little more about your proposal and decided to create a separate playlist in which the channels will be grouped simultaneously by country and by topic if it exist. 

Here is a new link - `https://raw.githubusercontent.com/freearhey/iptv/master/index.full.m3u`

**Comment by amirh123123** [comment]
in tv master m3u dont address to open files example 
#EXTM3U
#EXTINF:-1,Afghanistan
channels/af.m3u
#EXTINF:-1,Albania
channels/al.m3u
#EXTINF:-1,Algeria
channels/dz.m3u
dont address to open m3u countries

**Comment by freearhey** [comment]
I just checked this playlist in VLC Player and it works for me. If you have any other problems feel free to open a new issue.
