### ISSUE TITLE
new country play list

### ISSUE THREAD

**Issue by amirh123123** [freearhey/iptv#36]
please creat new country play list with oup genres example
#EXTM3U
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://aghaniaghani.com/images/logo.png" group-title="Afghanistan",Aghani Aghani
https://svs.itworkscdn.net/aghanilive/aghanilive/playlist.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="http://epiplay.com/wp-content/uploads/2019/01/atnnewslive-196x126.jpg" group-title="Afghanistan",Ariana News
https://d10rltuy0iweup.cloudfront.net/ATNNEWS/myStream/chunklist_w796472816.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://yt3.ggpht.com/a-/AN66SAyW491tR4WjLYsBfZk1MXuU8vBuV0RLcU8pWQ=s900-mo-c-c0xffffffff-rj-k-no" group-title="Afghanistan",Ariana TV
http://d2g7v53450s2i2.cloudfront.net/ATNUS/streamdelay/chunklist_w1314452267.m3u8?fluxustv.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://www.arianatelevision.com/wp-content/uploads/2017/08/logo-atn-new.png" group-title="Afghanistan",Ariana TV
https://d10rltuy0iweup.cloudfront.net/ATNNAT/myStream/chunklist_w2121902183.m3u8
and with out grouping buy genres and link address is 
https://raw.githubusercontent.com/freearhey/iptv/master/index.country.m3u

**Comment by amirh123123** [comment]
with out grouping by genres

**Comment by amirh123123** [comment]
just grouping by countries

**Comment by freearhey** [comment]
Playlist grouped by country already exists: `https://raw.githubusercontent.com/freearhey/iptv/master/index.m3u`

**Comment by freearhey** [comment]
I thought a little more and realized that you were right and I still have to make a separate playlist grouped only by country. 

And here is the new link: https://raw.githubusercontent.com/freearhey/iptv/master/index.country.m3u
