### ISSUE TITLE
question

### ISSUE THREAD

**Issue by amirh123123** [freearhey/iptv#37]
why remove grouping iptv by country and genres and remove link
https://raw.githubusercontent.com/freearhey/iptv/master/index.full.m3u
and remove grouping iptv channels by genres and remove link
https://raw.githubusercontent.com/freearhey/iptv/master/index.all.m3u
i like 3 1 tv full country and gernes 
2 tv by country 
and 3 tv genres thanks

**Comment by freearhey** [comment]
I have already returned `index.full.m3u` playlist. As for `index.all.m3u`, it was simply renamed to `index.topic.m3u`
