### ISSUE TITLE
Bad providers

### ISSUE THREAD

**Issue by Chris230291** [freearhey/iptv#38]
Hi. lots of sites seem to be getting stream from this server...
http://80.80.160.168/
Stuff here is not live though. Can you please blacklist?

Thnaks

**Comment by freearhey** [comment]
Can you give an exact example of such a link?

**Comment by Chris230291** [comment]
http://80.80.160.168/live/8/live.m3u8

**Comment by freearhey** [comment]
And what makes you think it's not live?

**Comment by Chris230291** [comment]
I know its not. 
Doesn't match EPG.
Has advertisement from months ago.
Repeats on a loop.

**Comment by exodiver** [comment]
Yes, the ESPN stream does not match the real time ESPN stream.

**Comment by freearhey** [comment]
Thanks for your help!
