### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by DanielAbsi** [freearhey/iptv#39]
Hi thank you for the channel, I realize when I see a channel it freeze and bug for few second and the resolution go to 144p. I don't know what is the probem if it is the file or the internet connection. I would like to streem fluidly TV in 1080p or in 4K if they have some of them. 
Thank you

**Comment by freearhey** [comment]
Could you give an exact example of such a link?

**Comment by freearhey** [comment]
Which channel do you mean?
