### ISSUE TITLE
Freearhey M3U URL in IPTV Bouquet Maker Plugin v0.8.2 

### ISSUE THREAD

**Issue by dumc1946** [freearhey/iptv#4]
I entered Freearhey M3U URL (https://raw.githubusercontent.com/freearhey/iptv/master/index.m3u) in IPTV Bouquet Maker Plugin v0.8.2 (https://www.suls.co.uk/enigma2-iptv-plugin/) but without success, failed to parse m3u data.  Using this in Zgemma H.2H Enigma2 box running OpenATV 6.2 with WooshBuild Infinity.

**Comment by freearhey** [comment]
I think this plugin just can't load playlists recursively. Try using a playlist for specific country, for example: `https://raw.githubusercontent.com/freearhey/iptv/master/channels/uk.m3u`

**Comment by dumc1946** [comment]
Many thanks for your prompt response.  I will try your suggestion and 
report back.
Donal

**Comment by dumc1946** [comment]
https://raw.githubusercontent.com/freearhey/iptv/master/channels/uk.m3u
Yes this worked perfectly and created UK bouquets.  I will try other 
countries as I would like the total 5000 channels.
Thank you.
Donal

**Comment by cigano333** [comment]
I want to thank you for this nice job you do

**Comment by haleez** [comment]
Thank you 
worked up to now

**Comment by panorama93** [comment]
The free IPTV-Org Playlists are the best ever and getting better every day.  Big thanks to Freearhey and all who have contributed to making these free Playlists the best in the world!

**Comment by frantdse** [comment]
2019!!
