### ISSUE TITLE
China

### ISSUE THREAD

**Issue by ericongsweekee** [freearhey/iptv#68]

**Comment by freearhey** [comment]
Could you describe the problem in a bit more detail?

**Comment by chamappuk** [comment]
I want a life time iptv. I have 1 link but it's lock with cloudflare will
great for both of us

**Comment by freearhey** [comment]
@chamappuk Sorry, but I don't understand what you mean.

**Comment by chamappuk** [comment]
I mean I have iptv link which is lock by the owner with cloudslare... Is
the best m3u file ever...i Wonder if u can unlock it.

**Comment by freearhey** [comment]
Honestly, this is the first time I've heard about blocking iptv using cloudflare.
