### ISSUE TITLE
Copyright issue

### ISSUE THREAD

**Issue by yang511** [freearhey/iptv#78]
How are you?
I used your channels for ios app that is streaming video player app.
But apple rejected my app because streaming video's copyright issue.
They informed me these channels has copyright
I think these are all free channels, but i have no proof data that channels are free.
If you have proof data that these channels are free, please let me know 
Thanks

**Comment by freearhey** [comment]
No, I don’t have any information about the copyright of these channels. This repository is just a collection of links to publicly accessible broadcasts.

**Comment by yang511** [comment]
Do you have any license of these channels?

**Comment by freearhey** [comment]
No, I don't have. You need a channel license only if you plan to broadcast it.

**Comment by yang511** [comment]
Please let me know where can i get channel license?

**Comment by freearhey** [comment]
Sorry but i don't know.

**Comment by yang511** [comment]
Ok, then thanks
