### ISSUE TITLE
FastoTV integration

### ISSUE THREAD

**Issue by topilski** [freearhey/iptv#8]
Hi, maybe https://fastotv.com will be interesting for you.

**Comment by freearhey** [comment]
What do you mean by integration?

**Comment by topilski** [comment]
@freearhey it will be good to have 1 big playlist with 'group-title="News",NHK World, Brazil'" which contains country.

**Comment by freearhey** [comment]
Well, I'll try to make one.

**Comment by topilski** [comment]
Thank you @freearhey

**Comment by freearhey** [comment]
Done.
https://github.com/freearhey/iptv/blob/master/index.all.m3u

**Comment by topilski** [comment]
@freearhey cool, thank you!

**Comment by topilski** [comment]
Please write to me on email.
